package common

const (
	// SYSTEM 相关信息
	SYSTEM_CHAT_INFO = "🍉 嗨，我是 WinDS Assistant\n🥝 我可以分析系统日志、CPU、GPU等系统数据趋势、硬盘文件结构与大小等"
	SYSTEM_DIALOG_ID_INFO = "🍔 <会话 ID>"
	SYSTEM_BACKEND_INFO = "🍕 <BACKEND>"
	SYSTEM_URL_INFO = "🍰 <URL>"
	SYSTEM_MODEL_INFO = "🍻 <MODEL>"
	SYSTEM_AGENT_STATUS_INFO = "🍺 <AGENT STATUS>"

	// CHAT 相关信息
	CHAT_USER_INFO = "\n🍩 <USER> :\n"
	CHAT_ASSISTANT_INFO = "\n🍲 <ASSISTANT> :\n"
	CHAT_END = "\n<对话结束>\n"
	CHAT_AGENT_MID = "\n中间结果:\n"
	CHAT_TERMINATE = "\n<对话终止>\n"

	// WIDGET 文本
	WIDGET_SETTING = "设置"
	WIDGET_CHAT_TERMINATE = "TERMINATE"
	WIDGET_NEW_CHAT = "NEW CHAT"
	WIDGET_COPY_CHAT = "COPY WINDOW"
	WIDGET_AGENT_SWITCH = "AGENT SWITCH"
	WIDGET_SEND = "SEND"
	WIDGET_INPUT_PLACEHOLDER = "给 WinDS Assistant 发送消息"
	WIDGET_LOADING = "加载中..."
	WIDGET_FORM_URL = "URL"
	WIDGET_FORM_APIKEY = "API 密钥"
	WIDGET_FORM_MODEL_SELECT = "选择模型"
	WIDGET_FORM_BACKEND = "API"
	WIDGET_BACKEND_SETTING = "大模型后端"
	WIDGET_CURRENT_MODEL = "当前模型"
	WIDGET_DIALOG_CONFIRM = "确认"
	WIDGET_DIALOG_CANCEL = "取消"
	WIDGET_DIALOG_SAVE = "保存"
	WIDGET_APP_NAME = "WinDS Assistant"
	WIDGET_REFRESH = "刷新配置"
	WIDGET_FASTCLIBOARD = "快捷指令"
	WIDGET_SKIP_TO_BOTTOM = "跳转底部"
)

var BACKEND_MAP = map[string]string{
	"ollama": 		"OLLAMA",
	"qwen": 		"通义千问",
	"volcengine": 	"火山引擎",
}